### ISSUE TITLE
Demo is not working on Chrome 43.0.2357.45 beta (64-bit)

### ISSUE THREAD

**Issue by smelnyk** [fbbdev/mp4analyzer.js#1]
Uncaught TypeError: Illegal invocation
Uncaught ReferenceError: MP4 is not defined

**Comment by fbbdev** [comment]
I'm sorry, I don't have time to install chrome beta and test it. Could you provide more details and error backtraces? Use this page https://fbbdev.io/mp4analyzer.js/debug.html

**Comment by smelnyk** [comment]
Sure:

Uncaught TypeError: Illegal invocation
(anonymous function) @ mp4analyzer.js:16 
proxyWebkitMethods  @ mp4analyzer.js:14 
checkFileAPI  @ mp4analyzer.js:32 
(anonymous function)  @ mp4analyzer.js:59 
(anonymous function) @ mp4analyzer.js:586

debug.html:6 Uncaught ReferenceError: MP4 is not defined
(anonymous function) @ debug.html:6

**Comment by fbbdev** [comment]
Fixed. Thank you for reporting.
